# Generated by Django 4.0.5 on 2022-06-16 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название авто')),
                ('year', models.CharField(blank=True, max_length=150, null=True, verbose_name='Год выпуска')),
                ('transmitter', models.CharField(blank=True, max_length=150, null=True, verbose_name='Коробка передач')),
                ('fuel_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вид топлива')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер телефона')),
                ('kilometers', models.CharField(blank=True, max_length=150, null=True, verbose_name='Пробег')),
                ('color', models.CharField(blank=True, max_length=150, null=True, verbose_name='цвет')),
                ('price', models.CharField(blank=True, max_length=150, null=True, verbose_name='цена')),
                ('engine_capacity', models.CharField(blank=True, max_length=150, null=True, verbose_name='Объем двигателя')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photo1/', verbose_name='Фото-1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photo2/', verbose_name='Фото-2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photo3/', verbose_name='Фото-3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='photo4/', verbose_name='Фото-4')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='photo5/', verbose_name='Фото-5')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано ли')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
